In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('minimum_eda_dataset.csv')

print("Dataset loaded successfully")

Dataset loaded successfully

In [3]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Property_Area
0,Male,Yes,0,Graduate,No,5000,0,120,Urban
1,Female,No,1,Graduate,Yes,3000,1500,100,Rural
2,Male,Yes,2,Not Graduate,No,4500,1200,130,Semiurban
3,Female,Yes,3+,Graduate,No,6000,1800,150,Urban
4,Male,No,0,Graduate,Yes,3500,0,90,Rural

In [4]:
df.tail()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Property_Area
0,Male,Yes,0,Graduate,No,5000,0,120,Urban
1,Female,No,1,Graduate,Yes,3000,1500,100,Rural
2,Male,Yes,2,Not Graduate,No,4500,1200,130,Semiurban
3,Female,Yes,3+,Graduate,No,6000,1800,150,Urban
4,Male,No,0,Graduate,Yes,3500,0,90,Rural

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             5 non-null      object
 1   Married            5 non-null      object
 2   Dependents         5 non-null      object
 3   Education          5 non-null      object
 4   Self_Employed      5 non-null      object
 5   ApplicantIncome    5 non-null      int64
 6   CoapplicantIncome  5 non-null      int64
 7   LoanAmount         5 non-null      int64
 8   Property_Area      5 non-null      object
dtypes: int64(3), object(6)
memory usage: 492.0+ bytes

In [6]:
df.describe()

       ApplicantIncome  CoapplicantIncome  LoanAmount
count         5.000000           5.000000    5.000000
mean       4400.000000         900.000000  118.000000
std        1193.733639         848.528137   23.874673
min        3000.000000           0.000000   90.000000
25%        3500.000000           0.000000  100.000000
50%        4500.000000        1200.000000  120.000000
75%        5000.000000        1500.000000  130.000000
max        6000.000000        1800.000000  150.000000

In [7]:
print(df.columns)

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Property_Area'],
      dtype='object')

In [8]:
categorical_cols = ['Gender', 'Married', 'Dependents', 'Education',
                    'Self_Employed', 'Property_Area']

for col in categorical_cols:
    unique_vals = df[col].unique()
    print(f"\nUnique values in '{col}': {unique_vals}")

Unique values in 'Gender': ['Male' 'Female']

Unique values in 'Married': ['Yes' 'No']

Unique values in 'Dependents': ['0' '1' '2' '3+']

Unique values in 'Education': ['Graduate' 'Not Graduate']

Unique values in 'Self_Employed': ['No' 'Yes']

Unique values in 'Property_Area': ['Urban' 'Rural' 'Semiurban']

In [9]:
df['Dependents'] = df['Dependents'].replace('3+', 3)

df['Dependents'] = pd.to_numeric(df['Dependents'],
                                 errors='coerce').astype('Int64')

print("Value counts in 'Dependents' after conversion:")
print(df['Dependents'].value_counts(dropna=False))

Value counts in 'Dependents' after conversion:
Dependents
0    2
1    1
2    1
3    1
Name: count, dtype: Int64

In [10]:
cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount']

for col in cols:
    print(f"\nStatistics for '{col}':")
    print(f"Mean: {df[col].mean():.2f}")
    print(f"Median: {df[col].median():.2f}")
    print(f"Mode: {df[col].mode().values}")
    print(f"Range: {df[col].max() - df[col].min():.2f}")
    print(f"Variance: {df[col].var():.2f}")
    print(f"Standard Deviation: {df[col].std():.2f}")

Statistics for 'ApplicantIncome':
Mean: 4400.00
Median: 4500.00
Mode: [3000 3500 4500 5000 6000]
Range: 3000.00
Variance: 1425000.00
Standard Deviation: 1193.73

Statistics for 'CoapplicantIncome':
Mean: 900.00
Median: 1200.00
Mode: [0]
Range: 1800.00
Variance: 720000.00
Standard Deviation: 848.53

Statistics for 'LoanAmount':
Mean: 118.00
Median: 120.00
Mode: [ 90 100 120 130 150]
Range: 60.00
Variance: 570.00
Standard Deviation: 23.87

In [11]:
# Applicants with income greater than 4000
high_income = df[df['ApplicantIncome'] > 4000]

print("Applicants with income greater than 4000:")
print(high_income)

Applicants with income greater than 4000:
   Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
0    Male     Yes           0      Graduate            No             5000
2    Male     Yes           2  Not Graduate            No             4500
3  Female     Yes           3      Graduate            No             6000

   CoapplicantIncome  LoanAmount Property_Area
0                  0         120         Urban
2               1200         130     Semiurban
3               1800         150         Urban

In [12]:
graduates = df[df['Education'] == 'Graduate']

print("Graduate applicants:")
print(graduates)

Graduate applicants:
   Gender Married  Dependents Education Self_Employed  ApplicantIncome  \
0    Male     Yes           0  Graduate            No             5000
1  Female      No           1  Graduate           Yes             3000
3  Female     Yes           3  Graduate            No             6000
4    Male      No           0  Graduate           Yes             3500

   CoapplicantIncome  LoanAmount Property_Area
0                  0         120         Urban
1               1500         100         Rural
3               1800         150         Urban
4                  0          90         Rural